/**
 * IDs list for all ui elements
 */
export enum UiIdsEnum {
  // Sign in form
  SIGN_IN_FORM_PASSWORD_ICON = 'SIGN_IN_FORM_PASSWORD_ICON',
  SIGN_IN_FORM_FORGOT_LINK = 'SIGN_IN_FORM_FORGOT_LINK',
  SIGN_IN_FORM_PASSWORD = 'SIGN_IN_FORM_PASSWORD',
  SIGN_IN_FORM_SUBMIT = 'SIGN_IN_FORM_SUBMIT',
  SIGN_IN_FORM_EMAIL = 'SIGN_IN_FORM_EMAIL',
  // Sign up form
  SIGN_UP_FORM_CONFIRM_PASSWORD_ICON = 'SIGN_UP_FORM_CONFIRM_PASSWORD_ICON',
  SIGN_UP_FORM_CONFIRM_PASSWORD = 'SIGN_UP_FORM_CONFIRM_PASSWORD',
  SIGN_UP_FORM_PASSWORD_ICON = 'SIGN_UP_FORM_PASSWORD_ICON',
  SIGN_UP_FORM_FIRST_NAME = 'SIGN_UP_FORM_FIRST_NAME',
  SIGN_UP_FORM_LAST_NAME = 'SIGN_UP_FORM_LAST_NAME',
  SIGN_UP_FORM_BACK_LINK = 'SIGN_UP_FORM_BACK_LINK',
  SIGN_UP_FORM_PASSWORD = 'SIGN_UP_FORM_PASSWORD',
  SIGN_UP_FORM_SUBMIT = 'SIGN_UP_FORM_SUBMIT',
  SIGN_UP_FORM_EMAIL = 'SIGN_UP_FORM_EMAIL',
  // New password form
  NEW_PASSWORD_FORM_CONFIRM_PASSWORD_ICON = 'NEW_PASSWORD_FORM_CONFIRM_PASSWORD_ICON',
  NEW_PASSWORD_FORM_NEW_PASSWORD_ICON = 'NEW_PASSWORD_FORM_NEW_PASSWORD_ICON',
  NEW_PASSWORD_FORM_CONFIRM_PASSWORD = 'NEW_PASSWORD_FORM_CONFIRM_PASSWORD',
  NEW_PASSWORD_FORM_NEW_PASSWORD = 'NEW_PASSWORD_FORM_NEW_PASSWORD',
  NEW_PASSWORD_FORM_BACK_LINK = 'NEW_PASSWORD_FORM_BACK_LINK',
  NEW_PASSWORD_FORM_SUBMIT = 'NEW_PASSWORD_FORM_SUBMIT',
  // Reset password
  RESET_PASSWORD_FORM_BACK_LINK = 'RESET_PASSWORD_FORM_BACK_LINK',
  RESET_PASSWORD_FORM_SUBMIT = 'RESET_PASSWORD_FORM_SUBMIT',
  RESET_PASSWORD_FORM_EMAIL = 'RESET_PASSWORD_FORM_EMAIL',
}
